# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhereUsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True)),
                ('where', models.CharField(choices=[('LIVINGROOM', 'Living Room'), ('KITCHEN', 'Kitchen Room'), ('POWDERROOM', 'Powder Room'), ('ANDREASBEDROOM', "Anddrea's Bedroom"), ('ELLIESBEDROOM', "Ellie's Bedroom"), ('MASTERBEDROOM', 'Master Bedroom'), ('MASTERBATH', 'Master Bath'), ('GIRLSBATH', "Girl's Bath"), ('GARAGE', 'Garage'), ('FRONTYARD', 'Front Yard'), ('BACKYARD', 'Back Yard')], max_length=15)),
            ],
        ),
    ]
