# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlistapp', '0003_wishlist_where'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='where',
            field=models.CharField(choices=[('LIVINGROOM', 'Living Room'), ('KITCHEN', 'Kitchen Room'), ('POWDERROOM', 'Powder Room'), ('ANDREASBEDROOM', "Andrea's Bedroom"), ('ELLIESBEDROOM', "Ellie's Bedroom"), ('MASTERBEDROOM', 'Master Bedroom'), ('MASTERBATH', 'Master Bath'), ('GIRLSBATH', "Girl's Bath"), ('GARAGE', 'Garage'), ('FRONTYARD', 'Front Yard'), ('BACKYARD', 'Back Yard')], max_length=15),
        ),
    ]
